% Generated by open-ontologies `fol` export.
%
% The translation is the one owl-lean's machine-checked adequacy theorem
% `OwlLean.adequacy` is about (axioms: propext, Classical.choice, Quot.sound;
% no sorry, no Mathlib). The CORRESPONDENCE between this emitter and that Lean
% translation is PINNED BY TESTS AND IS NOT ITSELF PROVED.
%
% `thing` and `lit` are the soft-typing predicates: object positions are
% relativised by `thing`, data positions by `lit`. The first two axioms are
% owl-lean's `background`; the `ind_typing_*` axioms are its `indAxioms`, and
% omitting them refutes adequacy outright (OwlLean.Refutations).
%
% A prover's verdict on this file is an ORACLE OPINION, not a certificate.
% Checking a superposition refutation needs a verified first-order calculus
% with unification, which does not exist in core Lean. Disagreement between
% a prover and this engine is a bug in one of the two and nothing here says
% which.
fof(background_1, axiom, ! [X0] : (~ (thing(X0) & lit(X0)))).
fof(background_2, axiom, ? [X0] : thing(X0)).
fof(ind_typing_1, axiom, thing('i:http://example.org/socrates')).
fof(owl_1_subClassOf, axiom, ! [X0] : (thing(X0) => ('c:http://example.org/Greek'(X0) => 'c:http://example.org/Person'(X0)))).
fof(owl_2_subClassOf, axiom, ! [X0] : (thing(X0) => ('c:http://example.org/Person'(X0) => 'c:http://example.org/Mortal'(X0)))).
fof(owl_3_classAssertion, axiom, (thing('i:http://example.org/socrates') & 'c:http://example.org/Greek'('i:http://example.org/socrates'))).
fof(goal_classAssertion, conjecture, (thing('i:http://example.org/socrates') & 'c:http://example.org/Mortal'('i:http://example.org/socrates'))).
