//! **The README's graph states figures, so the figures are re-derived.**
//!
//! `docs/assets/knowledge-graph.svg` is drawn from a real certified run over
//! `benchmark/reference/ies-core.ttl` and prints the counts in its legend:
//! how many triples were asserted, how many the fixpoint derived, and the
//! rules that derived them. It is the first picture on the README.
//!
//! Nothing about an SVG stops those drifting from the engine. So this runs the
//! reasoner over the same ontology and compares. The picture is regenerated by
//! `docs/assets/knowledge-graph.py` from a certificate directory, and this is
//! what makes forgetting to regenerate it a failure rather than a slow lie.
//!
//! The drawn EDGE counts are deliberately not re-derived here. They are a
//! projection of the certificate onto `rdfs:subClassOf`, which the generator
//! computes and this test would have to reimplement to check, and a second
//! implementation of the same projection agreeing with the first says very
//! little. The asserted and derived totals are the load-bearing numbers and
//! they come straight from the engine.

use open_ontologies::graph::GraphStore;
use open_ontologies::reason::{InferenceTarget, Reasoner};
use std::path::PathBuf;
use std::sync::Arc;

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn svg() -> String {
    std::fs::read_to_string(repo().join("docs").join("assets").join("knowledge-graph.svg"))
        .expect("read knowledge-graph.svg")
}

/// The integer the legend writes between `prefix` and `suffix`.
///
/// Anchored on both sides on purpose. Searching for a bare word finds the
/// first one in the file, and the first "derived" is in the `aria-label`,
/// which describes the picture in prose and carries no number. A loose anchor
/// made this test fail against a correct SVG.
fn drawn(prefix: &str, suffix: &str) -> u64 {
    let s = svg();
    let at = s
        .find(prefix)
        .unwrap_or_else(|| panic!("the legend no longer says {prefix:?}"));
    let rest = &s[at + prefix.len()..];
    let digits: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
    assert!(!digits.is_empty(), "no number after {prefix:?}");
    let after = &rest[digits.len()..];
    assert!(
        after.starts_with(suffix),
        "expected {suffix:?} after the number following {prefix:?}, found {:?}",
        &after[..suffix.len().min(after.len())]
    );
    digits.parse().expect("digits parse")
}

#[test]
fn the_graph_states_the_counts_a_real_run_produces() {
    let ttl = std::fs::read_to_string(repo().join("benchmark").join("reference").join("ies-core.ttl"))
        .expect("read ies-core.ttl");
    let graph = Arc::new(GraphStore::new());
    graph.load_turtle(&ttl, None).expect("ies-core.ttl must parse");

    let dir = std::env::temp_dir().join(format!("oo-kg-asset-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("scratch dir");

    let json = Reasoner::run_full(
        &graph,
        "rdfs",
        false,
        InferenceTarget::DefaultGraph,
        Some(dir.as_path()),
    )
    .expect("reason over ies-core.ttl");
    let r: serde_json::Value = serde_json::from_str(&json).expect("report is JSON");
    let cert = &r["certificate"];

    let asserted = cert["asserted"].as_u64().expect("certificate records asserted");
    let derived = cert["derivations"].as_u64().expect("certificate records derivations");

    assert_eq!(
        drawn("out of ", " asserted triples"),
        asserted,
        "the graph says {} asserted triples and the engine produced {asserted}. Regenerate it: \
         python3 docs/assets/knowledge-graph.py <dir>/asserted.tsv <dir>/derivations.tsv \
         docs/assets/knowledge-graph.svg",
        drawn("out of ", " asserted triples")
    );
    assert_eq!(
        drawn("asserted triples and ", " derived"),
        derived,
        "the graph says {} derived and the engine produced {derived}. Regenerate it the same way.",
        drawn("asserted triples and ", " derived")
    );

    // And the rules named in the legend are rules the run actually used.
    let by_rule = cert["by_rule"].as_object().expect("certificate records by_rule");
    let text = svg();
    for (rule, count) in by_rule {
        let claim = format!("{rule} x{count}");
        assert!(
            text.contains(&claim),
            "the run used {claim} and the legend does not say so. A legend naming some of the \
             rules is worse than one naming none, because a reader cannot tell which"
        );
    }
    let _ = std::fs::remove_dir_all(&dir);
}
